# Generated by Django 4.1 on 2023-10-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotografoa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotografia',
            old_name='data_fotografoa',
            new_name='data_fotografia',
        ),
    ]
